### PR TITLE
Client assertion signature configuration of identity broker is missing on new security admin console

### LINKED ISSUE #4144: Client assertion signature configuration of identity broker is missing on new security admin console
### Describe the bug

as below
keycloak/keycloak#14021

### Version

19.0.0

### Environment

_No response_

### Expected behavior

Client assertion signature configuration can be set on new security admin console as well.

### Actual behavior

_No response_

### How to Reproduce?

1. Create OIDC Identity Provider
2. Check Client Authentication

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by i7a7467**
## Motivation
keycloak/keycloak#14021

## Brief Description
Closes #4144 

## Verification Steps
No response

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes
I changed this one along with WRITING_TEST.md.

### CODE REVIEW

File: apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts [hunk 1]
```diff
@@ -35,6 +35,22 @@ export enum ClientAuthentication {
   jwtPrivKey = "Client secret sent as post",
 }
 
+export enum ClientAssertionSigningAlg {
+  algorithmNotSpecified = "Algorithm not specified",
```
Comment (ssilvert) [inline apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts:39]: Need to use i18n key you defined in the json file.

Comment (i7a7467) [reply apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts:39]: @ssilvert 
Thanks reply.
I do not believe it is necessary to use i18n key since this part of the code is the source of comparison for the cypress test.
Could you please provide some more details?

File: apps/admin-ui/cypress/e2e/identity_providers_oidc_test.spec.ts [hunk 2]
```diff
@@ -91,6 +92,10 @@ describe("OIDC identity provider test", () => {
       providerBaseAdvancedSettingsPage.assertOIDCClientAuthentication(
         ClientAuthentication.post
       );
+      //Cliient assertion signature algorithm
```
Comment (jonkoops) [inline apps/admin-ui/cypress/e2e/identity_providers_oidc_test.spec.ts:95]:
```suggestion
      // Client assertion signature algorithm
```

File: apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts (hunk 1 above)
Comment (jonkoops) [reply apps/admin-ui/cypress/support/pages/admin-ui/manage/identity_providers/ProviderBaseAdvancedSettingsPage.ts:39]: I'd say there is no need to do this for the tests, this is application code.

File: apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx [hunk 3]
```diff
@@ -76,6 +82,50 @@ export const OIDCAuthentication = ({ create = true }: { create?: boolean }) => {
...
+              maxHeight={200}
+              toggleId="clientAssertionSigningAlg"
+              onToggle={() => setOpenClientAuthSigAlg(!openClientAuthSigAlg)}
+              onSelect={(_, value) => {
+                field.onChange(value.toString());
+                setOpenClientAuthSigAlg(false);
+              }}
+              selections={field.value || t("algorithmNotSpecified")}
+              variant={SelectVariant.single}
+              aria-label={t("signatureAlgorithm")}
```
Comment (jonkoops) [inline apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx:110]: I think we can drop this label as the `Select` already has a `FormGroup` associated with it.

File: apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx [hunk 4]
```diff
@@ -76,6 +82,50 @@ export const OIDCAuthentication = ({ create = true }: { create?: boolean }) => {
...
+              isOpen={openClientAuthSigAlg}
+            >
+              <SelectOption selected={field.value === ""} key="" value="">
+                {t("algorithmNotSpecified")}
+              </SelectOption>
+              <>
```
Comment (jonkoops) [inline apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx:116]: Do we really need a fragment here?

File: apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx [hunk 5]
```diff
@@ -76,6 +82,50 @@ export const OIDCAuthentication = ({ create = true }: { create?: boolean }) => {
...
+                {providers.map((option) => (
+                  <SelectOption
+                    selected={option === field.value}
+                    key={option}
+                    value={option}
+                  ></SelectOption>
```
Comment (jonkoops) [inline apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx:122]: This element can be self-closing.
```suggestion
                  />
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Comment by jonkoops** [comment]
Looks good @i7a7467, just a couple of small nits.

File: apps/admin-ui/cypress/e2e/identity_providers_oidc_test.spec.ts (hunk 2 above)
Comment (i7a7467) [reply apps/admin-ui/cypress/e2e/identity_providers_oidc_test.spec.ts]: Thanks. I fixed it.

File: apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx (hunk 3 above)
Comment (i7a7467) [reply apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx]: You are correct. I fixed it.

File: apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx (hunk 5 above)
Comment (i7a7467) [reply apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx]: I fixed it.

File: apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx (hunk 4 above)
Comment (i7a7467) [reply apps/admin-ui/src/identity-providers/add/OIDCAuthentication.tsx]: I deleted fragment.
But I want to be able to choose `Algorithm not specified` , so I made some modifications.

**Comment by i7a7467** [comment]
@jonkoops 
Thanks for writing details. Could you confirm if?

**Review by jonkoops — APPROVED** [review]
I can't vouch for the Japanese translations, but everything looks good to me :+1:
