### PR TITLE
User events configuration fine tuning - #1562

### LINKED ISSUE #1562: [UX Review] Some fine-tuning of User event configs
### Describe the bug

Hi @edewit , there are some fine-tuning of **User event settings** in the **Realm settings** page. Please check them. Thanks.

1. We can get rid of the title. The same thing happens to the **Admin events settings** page.
Screen Shot 2021-11-11 at 3 26 57 PM

2. If users turn on the "Save events" but don't save the changes, the "Saved type" table below will not appear. 
Screen Shot 2021-11-11 at 3 39 35 PM

3. We can change "Delete" to "Remove" in the kebab menu.
Screen Shot 2021-11-16 at 3 01 40 PM

### Version

New admin UI

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by agagancarczyk**
## Motivation
Closes #1562

## Verification Steps

1. Go to `Realm settings >> Events >> User events settings`.
2. Verify that the header title `User events configuration` has been removed.
3. Set `Save events` to `On` and observe that the list of events only displays when the button `Save` is clicked.
4. In the events list, select the `three dots` button in the first row and verify that button is now reading `Remove`.
5. Go to `Admin events settings` and verify that the header title `Admin events configuration` has been removed.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

### CODE REVIEW

File: apps/admin-ui/src/realm-settings/event-config/EventsTab.tsx [hunk 1]
```diff
@@ -116,13 +116,15 @@ export const EventsTab = ({ realm }: EventsTabProps) => {
         eventConfig
       );
       setupForm({ ...events, ...eventConfig, adminEventsExpiration });
+      setEventsConfigSaved(true);
```
Comment (edewit) [inline apps/admin-ui/src/realm-settings/event-config/EventsTab.tsx:119]: this isn't right, it means that when I come back to the page I have to save the config again to see the adjust the messages.

**Review by edewit — CHANGES_REQUESTED** [review]

File: apps/admin-ui/src/realm-settings/event-config/EventsTab.tsx (hunk 1 above)
Comment (agagancarczyk) [reply apps/admin-ui/src/realm-settings/event-config/EventsTab.tsx]: thanks @edewit I overlooked this, but I think I found a fix. Please review it again. Thanks!

**Review by edewit — APPROVED** [review]
