### PR TITLE
Fixed listing flows alphabetically in addition to by type - #2765

### LINKED ISSUE #2765: [UX Review] List the authentication flow alphabetically
### Describe the bug

In the authentication list, all flows are divided into two parts, the first part is used by something and the other part is not used. All the flows in the 2 parts should be listed alphabetically. But in the current new UI, it doesn't like that. So we can fix it in the new UI.
Screen Shot 2022-06-06 at 16 36 15

### Version

Admin new UI

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by agagancarczyk**
## Motivation
Closes #2765

## Verification Steps

1. Go to `Authentication >> Flows`.
2. Verify that the items in addition to being listed by type (previous implementation) are now also listed alphabetically as requested in #2765

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

### CODE REVIEW

File: apps/admin-ui/src/authentication/AuthenticationSection.tsx [hunk 1]
```diff
@@ -40,6 +40,7 @@ import { addTrailingSlash } from "../util";
 import { getAuthorizationHeaders } from "../utils/getAuthorizationHeaders";
 
 import "./authentication-section.css";
+import useLocaleSort, { mapByKey } from "../utils/useLocaleSort";
```
Comment (jonkoops) [inline apps/admin-ui/src/authentication/AuthenticationSection.tsx:43]: Nit: this import should be moved up a bit.
```suggestion
import { getAuthorizationHeaders } from "../utils/getAuthorizationHeaders";
import useLocaleSort, { mapByKey } from "../utils/useLocaleSort";

import "./authentication-section.css";
```

File: apps/admin-ui/src/authentication/AuthenticationSection.tsx [hunk 2]
```diff
@@ -81,7 +82,12 @@ export default function AuthenticationSection() {
     );
     const flows = await flowsRequest.json();
 
-    return sortBy(flows as AuthenticationType[], (flow) => flow.usedBy?.type);
+    return sortBy(
+      flows
+        ? localeSort(flows as AuthenticationType[], mapByKey("alias"))
+        : ([] as AuthenticationType[]),
+      (flow) => flow.usedBy?.type
+    );
```
Comment (jonkoops) [inline apps/admin-ui/src/authentication/AuthenticationSection.tsx:90]: Couple of points here.

1. You can handle `flows` possibly being `undefined` with an early-return (removes the need to re-check it later on).
2. You can pass `AuthenticationType` as a generic to `localeSort` (removes the need to cast it twice).

E.g.:

```suggestion
    if (!flows) {
      return [];
    }

    return sortBy(
      localeSort<AuthenticationType>(flows, mapByKey("alias")),
      (flow) => flow.usedBy?.type
    );
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

**Review by jonkoops — APPROVED** [review]
