### PR TITLE
Realm email doesn't default to port 25

### LINKED ISSUE #3097: Realm Email doesn't default to port 25
### Describe the bug

Email configuration of the realm doesen't use the default port:

image

### Version

19.0.1

### Expected behavior

Emails should be able to be send with the default port 25 but it needs to be explicitly set 

### Actual behavior

Keycloak tries to send mails without a port:

```bash
2022-08-10 14:33:19,499 ERROR [org.keycloak.services.resources.admin.RealmAdminResource] (executor-thread-1095) Failed to send email
 com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtp.*****.com, 0; timeout 10000;
  nested exception is:
	java.net.SocketTimeoutException: connect timed out
```

### How to Reproduce?

1. configure SMTP settings and leave port to default (no entry)
2. try to send mail and watch the errors in the logs
3. set the port 25 and redo no. 2

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ssilvert**
## Motivation
Fixes #3097 

## Brief Description
In `Realm Settings --> Email`, the port was not being saved properly if left blank.  The back end is expecting a `null` value to signify default port.

## Verification Steps
See #3097

### CODE REVIEW

File: src/realm-settings/EmailTab.tsx [hunk 1]
```diff
@@ -93,6 +97,9 @@ export const RealmSettingsEmailTab = ({
       serverSettings[key] = mapperFn(serverSettings[key]);
     }
 
+    // For default value, back end is expecting null instead of 0
+    if (serverSettings["port"] === 0) serverSettings["port"] = null;
```
Comment (jonkoops) [inline src/realm-settings/EmailTab.tsx:101]: Should be able to do a regular property access here.
```suggestion
    if (serverSettings.port. === 0) serverSettings.port = null;
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: src/realm-settings/EmailTab.tsx (hunk 1 above)
Comment (ssilvert) [reply src/realm-settings/EmailTab.tsx:101]: I tried that.  VS Code didn't recognize the property.

serverSettings is of type `[x: string]: any;`

**Review by jonkoops — APPROVED** [review]

File: src/realm-settings/EmailTab.tsx (hunk 1 above)
Comment (jonkoops) [reply src/realm-settings/EmailTab.tsx]: Seemed to work here, I added a commit for it.
